// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu5aBVoZRDefzFx9-GJGBOjhIqykAOVfc',
    appId: '1:41772010:web:926b9f8b64b44cfe228893',
    messagingSenderId: '41772010',
    projectId: 'shoppingbabsenayoncoders',
    authDomain: 'shoppingbabsenayoncoders.firebaseapp.com',
    storageBucket: 'shoppingbabsenayoncoders.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkhQI013CZ8hBO0yneljdKF_nsIl-Hmgc',
    appId: '1:41772010:android:ee83ab64d9f7dd4a228893',
    messagingSenderId: '41772010',
    projectId: 'shoppingbabsenayoncoders',
    storageBucket: 'shoppingbabsenayoncoders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUU8_U7U6i1UlSGkZ3KUh9kyDXZqEByMA',
    appId: '1:41772010:ios:7a9f572be022ba0b228893',
    messagingSenderId: '41772010',
    projectId: 'shoppingbabsenayoncoders',
    storageBucket: 'shoppingbabsenayoncoders.appspot.com',
    iosBundleId: 'com.shoppingbabes.yuvraj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUU8_U7U6i1UlSGkZ3KUh9kyDXZqEByMA',
    appId: '1:41772010:ios:46d5f820549eb7f5228893',
    messagingSenderId: '41772010',
    projectId: 'shoppingbabsenayoncoders',
    storageBucket: 'shoppingbabsenayoncoders.appspot.com',
    iosBundleId: 'com.shoppingbabes.sbuser.RunnerTests',
  );
}
